// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var MainElm = require("./elm/Main.elm");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

var app = MainElm.Elm.Main;

function startElmApp(selector) {
  var el = document.querySelector(selector);
  var element;
  if (el == null) {
    throw [
          Caml_builtin_exceptions.invalid_argument,
          "Passed none to unrwap"
        ];
  } else {
    element = el;
  }
  var initArgs = {
    node: element,
    flags: "ReasonML"
  };
  return app.init(initArgs);
}

startElmApp("#app");

exports.app = app;
exports.startElmApp = startElmApp;
/* app Not a pure module */
